# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-23 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_begin',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_end',
        ),
        migrations.AddField(
            model_name='article',
            name='period',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Период'),
        ),
    ]
