# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-22 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=400, verbose_name='E-mail'),
        ),
    ]
