# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import trainers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('apelido', models.CharField(blank=True, max_length=200, null=True, verbose_name='Апелиду')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=trainers.models.get_uploaded_file_name, verbose_name='Фото')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Данные обновлены')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Данные созданы')),
            ],
        ),
    ]
