# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_trainer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Статус'),
        ),
    ]
