# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_articles', '0003_auto_20160717_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='detail_text',
        ),
    ]
