# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_articles', '0004_auto_20170327_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='period',
        ),
    ]
