# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_articles', '0005_remove_article_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f \u043f\u043e \u043a\u0430\u043f\u043e\u044d\u0439\u0440\u0435', 'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438 \u043f\u043e \u043a\u0430\u043f\u043e\u044d\u0439\u0440\u0435'},
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Description \u0441\u0442\u0430\u0442\u044c\u0438'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Keywords \u0441\u0442\u0430\u0442\u044c\u0438'),
        ),
        migrations.AddField(
            model_name='article',
            name='preview_text',
            field=models.TextField(blank=True, null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
