# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('preview_text', models.TextField(verbose_name='Описание анонса')),
                ('detail_text', models.TextField(verbose_name='Детальное описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=news.models.get_uploaded_file_name, verbose_name='Картинка')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Данные обновлены')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Данные созданы')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
