# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_cover',
        ),
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.get_uploaded_file_name, verbose_name='Обложка'),
        ),
    ]
