# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
    ]
