# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 07:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

from gallery.models import get_uploaded_file_name

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Название альбома')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание альбома')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Данные обновлены')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Данные созданы')),
            ],
            options={
                'ordering': ['updated', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Заголовок фото')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к фотографии')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Это обложка альбома')),
                ('img', models.ImageField(upload_to=get_uploaded_file_name, verbose_name='Картинка')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Данные обновлены')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Данные созданы')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.models.Album')),
            ],
            options={
                'ordering': ['updated', 'created'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.models.Category'),
        ),
    ]
