# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
