# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20160518_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Заголовок фото'),
        ),
    ]
