# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рожения'),
        ),
        migrations.AlterField(
            model_name='master',
            name='date_death',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
    ]
