# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 07:14
from __future__ import unicode_literals

from django.db import migrations, models

from slider.models import get_uploaded_file_name

class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='slider',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=get_uploaded_file_name, verbose_name='Картинка'),
        ),
    ]
