# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 07:20
from __future__ import unicode_literals

from django.db import migrations, models

from slider.models import get_uploaded_file_name

class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20160513_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(upload_to=get_uploaded_file_name, verbose_name='Картинка'),
        ),
    ]
