# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_slider_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
    ]
