# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160717_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Description \u0441\u0442\u0430\u0442\u044c\u0438'),
        ),
        migrations.AddField(
            model_name='new',
            name='keywords',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Keywords \u0441\u0442\u0430\u0442\u044c\u0438'),
        ),
    ]
