# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 10:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='filial',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 14, 10, 21, 59, 424070), verbose_name='Данные созданы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filial',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 14, 10, 22, 32, 741492), verbose_name='Данные обновлены'),
            preserve_default=False,
        ),
    ]
