# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filials', '0004_auto_20160515_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='map_coord_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Координата х на карте'),
        ),
        migrations.AddField(
            model_name='filial',
            name='map_coord_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Координата у на карте'),
        ),
    ]
