# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Rostov', 'Ростов-на-Дону'), ('Cimlyansk', 'Цимлянск'), ('Shahty', 'Шахты')], default='Rostov', max_length=300, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('email', models.CharField(blank=True, max_length=300, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=300, verbose_name='Телефон')),
                ('timetable', models.TextField(blank=True, null=True, verbose_name='Расписание')),
                ('trainer', models.ManyToManyField(blank=True, related_name='filial', related_query_name='filial', to='trainers.models.Trainer', verbose_name='Тренер')),
            ],
        ),
    ]
