# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filials', '0002_auto_20160514_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'ordering': ['id']},
        ),
    ]
