# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-21 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filials', '0005_auto_20160516_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=400, verbose_name='Номер телефона')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Данные обновлены')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Данные созданы')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filials.models.Filial', verbose_name='Филиал')),
            ],
        ),
    ]
