# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 16:38
from __future__ import unicode_literals

from django.db import migrations, models

from academy.models import get_uploaded_file_name

class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=get_uploaded_file_name, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Название видео'),
        ),
    ]
