# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_auto_20160524_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academy',
            options={'verbose_name': 'Академия', 'verbose_name_plural': 'Академия'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Раздел академии', 'verbose_name_plural': 'Раздел академии'},
        ),
        migrations.AlterModelOptions(
            name='subsection',
            options={'verbose_name': 'Подраздел академии', 'verbose_name_plural': 'Подраздел академии'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
