# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 07:35
from __future__ import unicode_literals

from django.db import migrations, models

from about.models import get_uploaded_file_name

class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='photos',
        ),
        migrations.AddField(
            model_name='about',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=get_uploaded_file_name, verbose_name='Картинка'),
        ),
    ]
