# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_you_get', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatyouget',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
