# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import what_you_get.models


class Migration(migrations.Migration):

    dependencies = [
        ('what_you_get', '0002_auto_20160513_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatyouget',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=what_you_get.models.get_uploaded_file_name, verbose_name='Иконка'),
        ),
    ]
