# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what_you_get', '0003_whatyouget_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatyouget',
            options={'ordering': ['updated', 'created']},
        ),
    ]
